<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="F_PressureSensorInToBar" Id="{ee464f70-e313-4580-902c-24224853dc35}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_PressureSensorInToBar : LREAL
VAR_INPUT
	fPressure : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_PressureSensorInToBar := fPressure*400/32767;]]></ST>
    </Implementation>
    <LineIds Name="F_PressureSensorInToBar">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>