<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{710c49b1-6c28-4dfa-b3ee-ba840c2a49f8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Commissioning();
P_ControlBox();
P_Filtering();
P_CraneControl();
P_ControlBlock();
P_Outputs();
P_Inputs();
P_RunClock();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="5" Count="1" />
      <LineId Id="23" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="19" Count="0" />
      <LineId Id="15" Count="0" />
      <LineId Id="27" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>